http:
  port: "8081"
  
  
american:
  host: "training4-american-api.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/"
  client_id: "d1374b15c6864c3682ddbed2a247a826"
  client_secret: "4a87fe7e2e43488c927372AEF981F066"


training:
  host: "localhost"
  port: "9090"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://localhost:9191/delta?wsdl"
  service: "DeltaFlightsService"
  port: "DeltaFlightsServiceImplPort"